imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.ini }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver:   pdo_sqlite
        memory:   true

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
