EmVista\EmVistaBundle\Entity\FormaPagamento:
    type: entity
    table: forma_pagamento
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: AUTO
    fields:
        codigo:
            type: string
            scale: 0
            length: 3
            unique: false
            nullable: false
            precision: 0
        valor:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        descricao:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        gatewayPagamento:
            targetEntity: EmVista\EmVistaBundle\Entity\GatewayPagamento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                gatewayPagamento_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
