EmVista\EmVistaBundle\Entity\ProjetoImagem:
    type: entity
    table: projeto_imagem
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        projeto:
            targetEntity: EmVista\EmVistaBundle\Entity\Projeto
            cascade: {  }
            mappedBy: null
            inversedBy: imagens
            joinColumns:
                projeto_id:
                    referencedColumnName: id
            orphanRemoval: false
        imagem:
            targetEntity: EmVista\EmVistaBundle\Entity\Imagem
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                imagem_id:
                    referencedColumnName: id
            orphanRemoval: false
        tipoProjetoImagem:
            targetEntity: EmVista\EmVistaBundle\Entity\TipoProjetoImagem
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_projeto_imagem_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
