EmVista\EmVistaBundle\Entity\StatusArrecadacao:
    type: entity
    table: status_arrecadacao
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: AUTO
    fields:
        nome:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        descricao:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
