EmVista\EmVistaBundle\Entity\TermoUso:
    type: entity
    table: termo_uso
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: AUTO
    fields:
        termoUso:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        dataCadastro:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        dataFim:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        ativo:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    lifecycleCallbacks: {  }
