EmVista\EmVistaBundle\Entity\TokenSenha:
    type: entity
    table: token_senha
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: AUTO
    fields:
        token:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        dataCadastro:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: data_cadastro
        dataExpiracao:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: data_expiracao
        ativo:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        usuario:
            targetEntity: EmVista\EmVistaBundle\Entity\Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
